#!/bin/bash
# X-IDS Vercel Deployment - Copy & Paste Commands

echo "🚀 X-IDS Vercel Deployment"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Follow these exact commands:"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Install Vercel CLI (one time)"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  npm i -g vercel"
echo ""
echo ""
echo "STEP 2: Navigate to deployment directory"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  cd /Users/aryantiwari/Documents/Zero_Day_Attack/vercel-deploy"
echo ""
echo ""
echo "STEP 3: Login to Vercel"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  vercel login"
echo ""
echo "  (Opens browser, follow prompts)"
echo ""
echo ""
echo "STEP 4: Deploy to production"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  vercel --prod"
echo ""
echo "  When asked:"
echo "    - Scope: Choose your account"
echo "    - Project name: xids-framework (or your choice)"
echo "    - Directory: ./ (default)"
echo ""
echo ""
echo "STEP 5: Wait for deployment"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  Watch terminal for completion..."
echo "  Will show: ✓ Production: https://your-url.vercel.app"
echo ""
echo ""
echo "STEP 6: Copy deployment URL"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  Example: https://xids-framework-abc123.vercel.app"
echo "  (Your actual URL will be different)"
echo ""
echo ""
echo "STEP 7: Update frontend API endpoint"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  File: /Users/aryantiwari/Documents/Zero_Day_Attack/vercel-deploy/public/index.html"
echo ""
echo "  Find line ~15 that says:"
echo "    const API_URL = \"https://your-deployment-name.vercel.app/api\";"
echo ""
echo "  Replace with your actual URL from Step 6"
echo ""
echo ""
echo "STEP 8: Deploy frontend update"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  cd /Users/aryantiwari/Documents/Zero_Day_Attack/vercel-deploy"
echo "  vercel --prod"
echo ""
echo ""
echo "STEP 9: Test your deployment"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  Open in browser: https://your-url.vercel.app"
echo "  Click: Quick Test tab"
echo "  Click: 🔴 Test Critical button"
echo "  Result: Should show threat in <2 seconds"
echo ""
echo ""
echo "STEP 10: Verify API health"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  curl https://your-url.vercel.app/api/health"
echo ""
echo "  Should return:"
echo "    {\"status\": \"healthy\", \"models_loaded\": [...]}"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ You're Done! Your X-IDS is now live on the internet! 🚀"
echo ""
echo "Share your URL with your team:"
echo "  https://your-url.vercel.app"
echo ""
